# Page settings

# baseurl = "http://example.org/"
languageCode = "en-us"
title = "John Doe Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = false
disableSitemap = false
disable404 = false

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Joey Marshall"
        tagline = "Data analyst"
        avatar = "headshot-150-square.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: jmarshall2@pewresearch.org"
        title = "Email"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+19037212650"
        title = "+1.903.721.2650"

       # [[params.contact.list]]
       # class = "website"
       # icon = "fa-globe"
       # url = "//portfoliosite.com"
       # title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/joey-marshall-26383236/"
        title = "joey-marshall-26383236"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/marsha5813"
        title = "github.com/marsha5813"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/joeydm"
        title = "@joeydm"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Ph.D. in Sociology (ABD)"
        college = "Purdue University"
        dates = "Expected 2019"

         [[params.education.list]]
        degree = "M.S. in Sociology"
        college = "Purdue University"
        dates = "2015"
        
        [[params.education.list]]
        degree = "M.S. in Sociology"
        college = "The University of Texas at Tyle"
        dates = "2013"

    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "French"
        level = "Professional"

        [[params.language.list]]
        language = "Russian"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I'm a quantitative data analyst with expertise in data visualization and predictive modeling. My favorite projects start with messy, unstructured data and end with interactive dashboards and written reports that distill complex information into easily digestible insights. I'm currently a Research Associate at Pew Research Center and am completing my PhD in Sociology at Purdue University.\n\n **Download my [resume](Marshall-Joey-resume.pdf) or my [full academic CV](Marshall-Joey-full-academic-CV.pdf).**"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Research Associate"
        dates = "2017 - Present"
        company = "Pew Research Center"
        details = "Data management; statistical analysis; data visualization (including Tableau dashboards); writing research reports and blog posts for a non-technical audience; communicating findings to the public including the media and national conferences."

        [[params.jobs.list]]
        position = "Research Assistant"
        dates = "2014 - 2017"
        company = "Center on Religion and Chinese Society, Purdue University."
        details = "Analyzed geospatial data on religion in China and prepared maps for an Atlas published by Brill; contributed to collaborative research projects; created and distribute the monthly newsletter; produced and hosted regular audio and video interviews with guest scholars."

        [[params.jobs.list]]
        position = "Managing Editor"
        dates = "2014 - 2017"
        company = "Review of Religion and Chinese"
        details = "Oversaw journal manuscripts from submission to publication; communicated with authors, production editor, and editor-in-chief to produce biannual journal issues."

        [[params.jobs.list]]
        position = "Teaching Assistant"
        dates = "2011-204"
        company = "Purdue University and The University of Texas at Tyler"
        details = "Undergraduate and graduate TA for both online and face-to-face courses. Lectured for courses including Introductory Sociology and Religion in America. Assisted in preparation of course materials. Graded assignments. Led discussion groups."
        
    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = false
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python & Django"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[params.skills.list]]
        skill = "Angular"
        level = "95%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "75%"

        [[params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Joey Marshall"
